export const dados = [
    {
        id: 1, 
        title_service: "Concerto de Torneiras e encanamento", 
        nome: "Carlos Silva", 
        categoria: "Encanador", 
        telefone: "+55 11 99988-7766", 
        cidade: "São Paulo", 
        estado: "SP", 
        descricao: "Profissional com 10 anos de experiência em reparos hidráulicos. Atendo residências e...",
        precoMin: 50,
        precoMax: 200,
    },
    {
        id: 2, 
        title_service: "Faxina residencial completa", 
        nome: "Maria Oliveira", 
        categoria: "Diarista", 
        telefone: "+55 11 96728-2605", 
        cidade: "Rio de Janeiro", 
        estado: "RJ", 
        descricao: "Limpeza profunda, organização e passadoria. Trabalho com dedicação e",
        precoMin: 50,
        precoMax: 100,
    },
    {
        id: 3, 
        title_service: "Bolos decorados para festas", 
        nome: "Ana Costa", 
        categoria: "Bolos e Doces", 
        telefone: "+55 21 98877-6655", 
        cidade: "Minas Gerais", 
        estado: "MG", 
        descricao: "Bolos personalizados para aniversários, casamentos e eventos. Diversos sabores e",
        precoMin: 50,
        precoMax: 200,
    },
    {
        id: 4, 
        title_service: "Instalação e manutenção elétrica", 
        nome: "Pedro Santos", 
        categoria: "Eletricista", 
        telefone: "+55 21 98877-6655", 
        cidade: "Curitiba", 
        estado: "PR", 
        descricao: "Eletricista certificado. Instalação de tomadas, chuveiros, disjuntores, iluminação",
        precoMin: 50,
        precoMax: 200,
    },
    {
        id: 5, 
        title_service: "Pintura residencial e comercial", 
        nome: "João Ferreira", 
        categoria: "Pintor", 
        telefone: "+55 21 98877-6655", 
        cidade: "Salvador", 
        estado: "BA", 
        descricao: "Pintura interna e externa com acabamento profissional. Trabalho com tintas de primeir",
        precoMin: 50,
        precoMax: 200,
    },
    {
        id: 6, 
        title_service: "Aulas particulares de matemática", 
        nome: "Lucas Mendes", 
        categoria: "Aulas Particulares", 
        telefone: "+55 21 98877-6655", 
        cidade: "Porto Alegre", 
        estado: "RS", 
        descricao: "Professor formado em matemática. Aulas para ensino fundamental, médio e pré-escola",
        precoMin: 50,
        precoMax: 200,
    },
];